HEADER:
  label: "Contact"

LOCATION:
  embed: "google.com/maps/place/Marquis+at+Waterview/data=!4m2!3m1!1s0x0:0x21768ead0fd84c2d?sa=X&ved=1t:2428&ictx=111"

FORM:
  label: "Contact Form"
  fields:
    - name: "Sai Premanvitha Kadiyala"
    - email: "saipremanvitha.k@savemymails.com"
    - message: "Your message"
    - submit: "Send message"
