HEADER:
  label: "Contact"

LOCATION:
  embed: "https://www.google.com/maps/place/Marquis+at+Waterview/@32.9982814,-96.7336076,17z/data=!3m1!4b1!4m6!3m5!1s0x864c18b0b18a0377:0x21768ead0fd84c2d!8m2!3d32.9982814!4d-96.7336076!16s%2Fg%2F1tf7h1tk?entry=ttu&g_ep=EgoyMDI2MDIxMS4wIKXMDSoASAFQAw%3D%3D"

FORM:
  label: "Contact Form"
  fields:
    - name: "Sai Premanvitha Kadiyala"
    - email: "saipremanvitha.k@savemymails.com"
    - message: "Your message"
    - submit: "Send message"
