HEADER:
   label: "Portfolio"

PROJECTS:
   - title: "Financial-Market-Forecasting"
     category: "Time Series Forecasting"
     image: "https://i.imgur.com/ANDVQ4o.png"
     url: "https://github.com/Premanvitha2/Financial-Market-Forecasting"

   - title: "Anime_Recommendation_MLOps"
     category: "MLOps"
     image: "https://imgur.com/2nNXhDN.png"
     url: "https://github.com/Premanvitha2/Anime_Recommendation_MLOps"

   - title: "Gen AI"
     category: "Mobile development"
     image: "https://imgur.com/7110Lj1.png"
     url: "https://github.com/Premanvitha2/Gen-AI/tree/main/Gen-AI-main"

   - title: "Churn_Prediction "
     category: "Mobile development"
     image: "https://imgur.com/t5T5Ixa.png"
     url: "https://github.com/Premanvitha2/Churn_Prediction/tree/main/Customer-Churn-Prediction-main"

   - title: "sales_Dashboard-PowerBI"
     category: "PowerBI"
     image: "https://imgur.com/kyHrBGk.png"
     url: "https://github.com/Premanvitha2/sales_Dashboard-PowerBI"

   - title: "Zomato-Restaurant-Data-Analysis-using-Streamlit"
     category: "Data Analysis"
     image: "config/assets/projects/project-1.jpg"
     url: "https://github.com/Premanvitha2/Zomato-Restaurant-Data-Analysis-using-Streamlit/tree/main/Zomato-Restaurant-Data-Analysis-using-Streamlit-main"

   - title: "Orizon"
     category: "Web development"
     image: "config/assets/projects/project-2.png"
     url: "https://github.com/ivansaul/flutter_todo_app#screenshots"
