HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2023 — 2025"
      institution: "University of Texas at Dallas"
      description: "Graduated with Masters in Computer Science with specialization in Data Science"
    - period: "2018 — 2022"
      institution: "Gokaraju rangaraju Institute of Engineering and Technology"
      description: "Completed coursework in Electronics and Communication Engineering"
    
EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2020 — 2023"
      position: "AI ML Engineer"
      description: "Built and deployed machine learning and NLP solutions to improve demand forecasting, inventory optimization, pricing strategy, and customer insights for large-scale retail clients"
    - period: "2024 — Present"
      position: "Data Scientist"
      description: "Developed NLP-driven pipelines and machine learning risk models to monitor credit portfolios and automate compliance workflows."


SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Web Design"
      proficiency: "80%"
    - skill: "Graphic Design"
      proficiency: "70%"
    - skill: "Branding"
      proficiency: "90%"
    - skill: "WordPress"
      proficiency: "50%"
