HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2023 — 2025"
      institution: "University of Texas at Dallas"
      description: "Graduated with Masters in Computer Science with specialization in Data Science"
    - period: "2018 — 2022"
      institution: "Gokaraju rangaraju Institute of Engineering and Technology"
      description: "Completed coursework in Electronics and Communication Engineering"
    
EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2020 — 2023"
      position: "AI ML Engineer"
      description: "Built and deployed machine learning and NLP solutions to improve demand forecasting, inventory optimization, pricing strategy, and customer insights for large-scale retail clients"
    - period: "2024 — Present"
      position: "Data Scientist"
      description: "Developed NLP-driven pipelines and machine learning risk models to monitor credit portfolios and automate compliance workflows."


SKILLS:
  enabled: true
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Language and Tools: Python, R, SQL, C, Spark, Vertex AI, Generative AI"
    - skill: "IDEs: Visual Studio Code, Jupyter Notebook, PyCharm"
    - skill: "ML Algorithms: Linear Regression, Logistic Regression, Decision Trees, Random Forests, XGBoost, SVM, K-Means, Naive Bayes, PCA"
    - skill: "Deep Learning: CNN, RNN, LSTM, Transformers (BERT, GPT, T5, LLAMA), Hugging Face, Stable Diffusion, Generative AI (GenAI), OpenCV, LangChain"
    - skill: "Packages: NumPy, Pandas, Scikit-learn, TensorFlow, PyTorch, Keras, Seaborn, Matplotlib, Plotly, SciPy, MLflow, NLTK, spaCy"
    - skill: "Cloud Technology: AWS (EC2, S3, Lambda, SageMaker, EMR, DynamoDB), GCP (BigQuery, Vertex AI)"
    - skill: "Big Data & Data Engineering: Apache Spark, Databricks, Snowflake, Airflow"
    - skill: "MLOps & Model Deployment: Docker, Kubernetes, CI/CD Pipelines, RESTful APIs"
    - skill: "Visualization Tools: Tableau, Power BI, Google Data Studio, Matplotlib, Seaborn, Plotly, Advanced Excel "
    - skill: "Database: PostgreSQL, MySQL, SQL Server, MongoDB, Cassandra, SPSS"
